spring.application.name=api

### Spring Boot Actuator settings
management.endpoints.web.exposure.include=health,info,metrics,env,beans,loggers,threaddump

############# Enable H2 Database browser console #################
##http://localhost:port/h2-console/
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:springboot
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.use_sql_comments=true

## SHOW SQL REQUEST PARAMETERS

logging.level.root=info
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#management.endpoints.web.exposure.include=*

#HikariCP settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.max-lifetime=600000